name: Reset_Games_Won_by_Day
on: 
  schedule:
     - cron: '2 * * * *'
jobs:
  reset_games:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://asia-southeast2-findmymines.cloudfunctions.net/resetAllUsersGamesWon?timeRange=day
