name: Reset Games Won by Day
on: 
  schedule:
     - cron: '0 0 * * *'
jobs:
  reset_games_day:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://asia-southeast2-findmymines.cloudfunctions.net/resetAllUsersGamesWon?timeRange=day
